FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import url_base_patterns
from api.fetch.urls import routerFetch
from api.people.urls import url_user_patterns
from api.TTapp.urls import routerTTapp
from api.celcat.urls import routerCelcat

# V1...
from api.v1.urls import url_V1_patterns

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r"breakingnews", views.BreakingNewsViewSet)
routerDisplayweb.register(r"moduledisplays", views.ModuleDisplaysViewSet)
routerDisplayweb.register(
    r"trainingprogrammedisplays", views.TrainingProgrammeDisplaysViewSet
)
routerDisplayweb.register(r"groupdisplays", views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register("bknews", views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register("quote/random", views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register("quote", views.QuoteViewSet)
routerExtra.register("week-infos", views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################


urlpatterns = [
    path("", views_base.LoginView.as_view(), name="api_root"),
    path("logout/", views_base.LogoutView.as_view()),
    path(
        "backoffice/", login_required(TemplateView.as_view(template_name="logout.html"))
    ),
    path("base/", include((url_base_patterns, "api"), namespace="base")),
    path("user/", include((url_user_patterns, "api"), namespace="people")),
    # path("display/", include(routerDisplayweb.urls)),
    path("ttapp/", include((routerTTapp.urls, "api"), namespace="ttapp")),
    path("fetch/", include((routerFetch.urls, "api"), namespace="fetch")),
    # path("rest-auth/", include("dj_rest_auth.urls")),
    # path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("rooms/", include((routerRooms.urls, "api"), namespace="rooms")),
    path("courses/", include((routerCourses.urls, "api"), namespace="course")),
    path("groups/", include((routerGroups.urls, "api"), namespace="groups")),
    # path("extra/", include((routerExtra.urls, "api"), namespace="extra")),
    # path(
    #     "roomreservations/",
    #     include((routerRoomReservation.urls, "api"), namespace="roomreservations"),
    # ),
    path("v1/", include((url_V1_patterns, "api"), namespace="V1")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "doc/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path("celcat/", include((routerCelcat.urls, "api"), namespace="celcat")),
]

FlOpEDT/configuration/urls.py
from django.urls import path

from . import views

app_name = "configuration"

urlpatterns = [
    path("", views.configuration, name="configuration"),
    path("upload_config", views.import_config_file, name="ul_config"),
    path("upload_planif", views.import_planif_file, name="ul_planif"),
    path("download_config", views.get_config_file, name="dl_config"),
    path("download_planif", views.get_planif_file, name="dl_planif"),
    path(
        "mk_and_dl_blank_planif",
        views.mk_and_dl_planif,
        {"with_courses": False},
        name="mk_and_dl_blank_planif",
    ),
    path(
        "mk_and_dl_fullfilled_planif",
        views.mk_and_dl_planif,
        {"with_courses": True},
        name="mk_and_dl_fullfilled_planif",
    ),
    path(
        "mk_and_dl_fullfilled_database_file",
        views.mk_and_dl_database_file,
        name="mk_and_dl_fullfilled_database_file",
    ),
]

FlOpEDT/flopeditor/urls.py
# -*- coding: utf-8 -*-
"""
Python versions: Python 3.6

This file is part of the FlOpEDT/FlOpScheduler project.
Copyright (c) 2017
Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program. If not, see
<http://www.gnu.org/licenses/>.

You can be released from the requirements of the license by purchasing
a commercial license. Buying such a license is mandatory as soon as
you develop activities involving the FlOpEDT/FlOpScheduler software
without disclosing the source code of your own applications.


This module is used to declare the urls related to flop!EDITOR, an app used
to manage a department statistics for FlOpEDT.
"""

from django.urls import path

from . import crud, views

app_name = "flopeditor"

urlpatterns = [
    # directly reachable by users
    # ---------------------------
    path("", views.home, name="flopeditor-home"),
    path("flopeditor-help/", views.flopeditor_help, name="flopeditor-help"),
    path(
        "<slug:department_abbrev>/",
        views.department_default,
        name="flopeditor-department-default",
    ),
    path(
        "<slug:department_abbrev>/salles",
        views.department_rooms,
        name="flopeditor-department-rooms",
    ),
    path(
        "<slug:department_abbrev>/intervenants",
        views.department_tutors,
        name="flopeditor-department-tutors",
    ),
    path(
        "<slug:department_abbrev>/categories-de-salles",
        views.department_room_types,
        name="flopeditor-department-room-types",
    ),
    path(
        "<slug:department_abbrev>/attributs-de-salles",
        views.department_room_attributes,
        name="flopeditor-department-room-attributes",
    ),
    path(
        "<slug:department_abbrev>/groupes-structuraux",
        views.department_student_structural_groups,
        name="flopeditor-department-student-structural-groups",
    ),
    path(
        "<slug:department_abbrev>/groupes-transversaux",
        views.department_student_transversal_groups,
        name="flopeditor-department-student-transversal-groups",
    ),
    path(
        "<slug:department_abbrev>/natures",
        views.department_student_group_types,
        name="flopeditor-department-student-group-types",
    ),
    path(
        "<slug:department_abbrev>/promos",
        views.department_training_programmes,
        name="flopeditor-department-training-programmes",
    ),
    path(
        "<slug:department_abbrev>/etudiants",
        views.department_students,
        name="flopeditor-department-students",
    ),
    path(
        "<slug:department_abbrev>/modules",
        views.department_modules,
        name="flopeditor-department-modules",
    ),
    path(
        "<slug:department_abbrev>/types-de-cours",
        views.department_course_types,
        name="flopeditor-department-course-types",
    ),
    path(
        "<slug:department_abbrev>/contraintes-de-debut",
        views.department_course_start_times_constraints,
        name="flopeditor-department-course-start-times-constraints",
    ),
    path(
        "<slug:department_abbrev>/semestres",
        views.department_periods,
        name="flopeditor-department-periods",
    ),
    path(
        "<slug:department_abbrev>/parameters",
        views.department_parameters,
        name="flopeditor-department-parameters",
    ),
    path(
        "<slug:department_abbrev>/parameters/edit",
        views.department_parameters_edit,
        name="flopeditor-department-parameters-edit",
    ),
    path(
        "<slug:department_abbrev>/delete",
        views.department_delete,
        name="flopeditor-department-delete",
    ),
    # exchanges with the db via django
    # --------------------------------
    path(
        "ajax/create-department",
        views.ajax_create_department,
        name="flopeditor-ajax-create-department",
    ),
    path(
        "ajax/update-department",
        views.ajax_update_department,
        name="flopeditor-ajax-update-department",
    ),
    path(
        "ajax/parameters-edit/<slug:department_abbrev>",
        views.ajax_edit_parameters,
        name="flopeditor-ajax-edit-department-parameters",
    ),
    path(
        "ajax/update-profil",
        views.ajax_update_profil,
        name="flopeditor-ajax-update-profil",
    ),
    # exchanges with the CRUD
    # --------------------------------
    path(
        "<slug:department_abbrev>/crud/rooms",
        crud.crud_rooms,
        name="flopeditor-crud-rooms",
    ),
    path(
        "<slug:department_abbrev>/crud/tutors",
        crud.crud_tutors,
        name="flopeditor-crud-tutors",
    ),
    path(
        "<slug:department_abbrev>/crud/room_types",
        crud.crud_room_types,
        name="flopeditor-crud-room-types",
    ),
    path(
        "<slug:department_abbrev>/crud/room_attributes",
        crud.crud_room_attributes,
        name="flopeditor-crud-room-attributes",
    ),
    path(
        "<slug:department_abbrev>/crud/group_type",
        crud.crud_student_group_type,
        name="flopeditor-crud-student-group-type",
    ),
    path(
        "<slug:department_abbrev>/crud/student_structural_group",
        crud.crud_student_structural_group,
        name="flopeditor-crud-student-structural-group",
    ),
    path(
        "<slug:department_abbrev>/crud/student_transversal_group",
        crud.crud_student_transversal_group,
        name="flopeditor-crud-student-transversal-group",
    ),
    path(
        "<slug:department_abbrev>/crud/students",
        crud.crud_students,
        name="flopeditor-crud-students",
    ),
    path(
        "<slug:department_abbrev>/crud/modules",
        crud.crud_module,
        name="flopeditor-crud-modules",
    ),
    path(
        "<slug:department_abbrev>/crud/training_programmes",
        crud.crud_training_programmes,
        name="flopeditor-crud-training-programmes",
    ),
    path(
        "<slug:department_abbrev>/crud/courses",
        crud.crud_course,
        name="flopeditor-crud-courses",
    ),
    path(
        "<slug:department_abbrev>/crud/start_times_constraints",
        crud.crud_course_start_times_constraints,
        name="flopeditor-crud-start-times-constraints",
    ),
    path(
        "<slug:department_abbrev>/crud/periods",
        crud.crud_periods,
        name="flopeditor-crud-periods",
    ),
]

FlOpEDT/configuration/models.py
# from django.db import models

# Create your models here.

FlOpEDT/configuration/forms.py
from django import forms
from django.core.validators import RegexValidator


DAYS = [
    ("m", "Monday"),
    ("tu", "Tuesday"),
    ("w", "Wenesday"),
    ("th", "Thursday"),
    ("f", "Friday"),
]

validator_time = RegexValidator(r"^\d{2}:\d{2}$", "Must be as 00:00")


class ImportFile(forms.Form):
    file = forms.FileField()


class ImportPlanif(forms.Form):
    fichier = forms.FileField()


class ImportConfig(forms.Form):
    # nom = forms.SlugField()
    # abbrev = forms.CharField(max_length=7)
    # day_start_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # day_end_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # lunch_start_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # lunch_end_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # days = forms.MultipleChoiceField(
    #     required=True,
    #     widget=forms.CheckboxSelectMultiple,
    #     choices=DAYS,
    # )
    fichier = forms.FileField()

FlOpEDT/configuration/templates/configuration/configuration.html
{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
    {% load static %}
    {% load i18n %}
    <link rel="stylesheet" href="{% static 'configuration/style.css' %}"/>
    <script>
        let departments = {{ departments|safe }};
        let training_periods = {{ training_periods|safe }};
        let scheduling_periods = {{ scheduling_periods|safe }};
        let current_year = {{ current_year }};
        let next_year = {{current_year|add:"1"}};
    </script>
    <script type="text/javascript" src="{% static 'configuration/configuration_vars.js' %}"></script>
    <h1>{% trans "Step 1 - Database configuration (teachers, groups, rooms, course types, etc.)" %}</h1>
    <h2>{% trans "Option A: Using a spreadsheet file" %}</h2>
    <div class="step">
        <h3>{% trans "Configuration file canvas" %}</h3>
        <p>{% trans "Download and then complete the file below." %}</p>
            {% trans "Click to download the empty configuration file" %}
            <a href="{% url "configuration:dl_config" %}"><button id="btn_config_1">{% trans "Download"%}</button></a>
        <br/>
        <br/>
        {% trans "Click to make and download a new fullfilled database file" %}
        {% trans " (it may last several minuts)." %}
        <form action="{% url 'configuration:mk_and_dl_fullfilled_database_file' %}">
        <select name="department"  id="dropdown_dpt_1">
            {% for depart in departments %}
                <option value={{ depart.abbrev }} >{{ depart.name }}</option>
            {% endfor %}
        </select>
        <input id="btn_dl_database_file" type="submit" value={% trans "Make_and_download" %}>
        </form>
    </div>

    <div class="step">
        <h3>{% trans "Configuration file completed" %}</h3>
        <p>{% trans "Upload the completed configuration file." %}<br>
        {% trans "Only xlsx format is accepted."%}</p>
        <form action="{% url "configuration:ul_config" %}" method="post" enctype="multipart/form-data" id="config">
                {% csrf_token %}
            <fieldset>
                <label>{% trans "Department" %}</label><br>
                <input type="radio" name="radio_creations" value="1" required><span>{% trans "Create" %}</span>
                <input type="radio" name="radio_creations" value="2" required><span>{% trans "Edit" %}</span><br>
                <div id="depart_choice"></div>
                {{ form_config }}
                <input type="submit" value={% trans "Import" %}>
            </fieldset>
        </form>

        <div id="error_config">
          <h4>{% trans "Verdict :"%}</h4>
          <p></p>
        </div>
    </div>
    <h2>{% trans "Option B: With Flopeditor" %}</h2>
    <div class="step">
      <p><a href="{% url 'flopeditor:flopeditor-home' %}">{% trans "Click here" %}</a> {% trans " to go to Flopeditor."%} <br>
      {% trans "If you need help, you can consult the Flopeditor documentation on " %} <a href="{% url 'flopeditor:flopeditor-help' %}">{% trans "this page." %}</a>.</p>
    </div>

    <h1>{% trans "Step 2 - Plan the lessons (which lesson in which week, which teacher gives which lesson)" %}</h1>
    <div class="step">
    <h3>{% trans "Template for the planning file from the configuration file" %}</h3>
        {% trans "Click to download the current planning file outline" %}
        <form action="{% url 'configuration:dl_planif' %}">
        <select name="departments"  id="dropdown_dpt_2">
            {% for depart in departments %}
                <option value={{ depart.abbrev }} >{{ depart.name }}</option>
            {% endfor %}
        </select>
        <input id="btn_dl_planif" type="submit" value={% trans "Download" %}>
        </form>
        <br/>
        {% trans "Click to make and download a new blank planning file outline" %}
        {% trans " (it may last several minuts)." %}
        <form action="{% url 'configuration:mk_and_dl_blank_planif' %}">
        <select name="departments"  id="dropdown_dpt_3">
            {% for depart in departments %}
                <option value={{ depart.abbrev }} >{{ depart.name }}</option>
            {% endfor %}
        </select>
        <input id="btn_dl_planif" type="submit" value={% trans "Make_and_download" %}>
        </form>
        <br/>
        {% trans "Click to make and download a new fullfilled planning file outline" %}
        {% trans " (it may last several minuts)." %}
        <form action="{% url 'configuration:mk_and_dl_fullfilled_planif' %}">
        <select name="departments"  id="dropdown_dpt_4">
            {% for depart in departments %}
                <option value={{ depart.abbrev }} >{{ depart.name }}</option>
            {% endfor %}
        </select>
        <input id="btn_dl_planif" type="submit" value={% trans "Make_and_download" %}>
        </form>

    </div>

    <div class="step">
<!--        <form action="/configuration/import_planif_file/" method="post" enctype="multipart/form-data" id="config_2">-->
        <fieldset>
            <legend> <h3>{% trans "Completed planning file" %}</h3> </legend>
            <p>{% trans "Upload the completed planning file." %} ({% trans "Only xlsx format is accepted." %})</p>
            <form action="{% url "configuration:ul_planif" %}"
                  method="post"
                  enctype="multipart/form-data"
                  id="planif">
                {% csrf_token %}
                <select name="departments" id="dropdown_dpt_5">
                    {% for depart in departments %}
                        <option value={{ depart.abbrev }} >{{ depart.name }}</option>
                    {% endfor %}
                </select>
                </br></br>
                {{ form_planif }}
                </br>
                </br>
                    <div id="choose_training_periods">
                        <input type="checkbox" id="choose_training_periods" name="choose_training_periods"/>
                            <label for="choose_training_periods">{% trans "Only for training periods " %}
                                <select multiple name="training_periods" id="dropdown_training_periods"> </select>
                            </label>
                    </div>
                </br>
                </br>
                <div id="choose_scheduling_periods">
                    <input type="checkbox" id="choose_scheduling_periods" name="choose_scheduling_periods"/>
                        <label for="choose_scheduling_periods">{% trans "Only for scheduling periods " %}
                            <select multiple name="scheduling_periods" id="dropdown_scheduling_periods"> </select>
                        </label>
                </div>
                </br>
                <input type="checkbox" id="stabilize" name="stabilize"/>
                <label for="stabilize">{% trans "Stabilization ?" %}</label>
                </br></br>
                <input type="checkbox" id="assign_colors" name="assign_colors"/>
                <label for="assign_colors">{% trans "(Re)assign colors ?" %}</label>
                </br></br>
                <input type="submit"
                       id="submitImport"
                       onclick="return confirm(
                           confirm_text.intro + '\n\n' +
                           translated_department + confirm_text.department + '\n' +
                           translated_training_periods + confirm_text.training_periods + '\n' +
                           translated_weeks + confirm_text.weeks)"
                       value={% trans "Import" %}>
            </form>
        </fieldset>
        <div id="error_planif">
          <h4>{% trans "Verdict :" %}</h4>
          <p></p>
        </div>
    </div>

<script type="text/javascript" src="{% static 'configuration/configuration.js' %}"></script>
{% endblock %}